use std::collections::HashMap;
use std::process::Stdio;
use std::sync::Arc;

use parking_lot::Mutex;
use serde_json::json;
use tauri::{AppHandle, Emitter, State};
use tokio::io::{AsyncBufReadExt, AsyncWriteExt, BufReader};
use tokio::process::{Child, Command};
use tokio::sync::oneshot;

/// Tracks live `claude` subprocess runs so the frontend can cancel mid-stream.
/// Keyed by `request_id` (a UUID generated by the frontend per turn).
pub struct AgentState {
    pub runs: Arc<Mutex<HashMap<String, RunHandle>>>,
}

impl Default for AgentState {
    fn default() -> Self {
        Self {
            runs: Arc::new(Mutex::new(HashMap::new())),
        }
    }
}

pub struct RunHandle {
    pub kill: Option<oneshot::Sender<()>>,
}

fn map_permission_mode(mode: &str) -> &'static str {
    match mode {
        "accept" => "acceptEdits",
        "bypass" => "bypassPermissions",
        _ => "plan",
    }
}

#[tauri::command]
pub async fn claude_send(
    app: AppHandle,
    state: State<'_, AgentState>,
    request_id: String,
    chat_id: String,
    cwd: String,
    permission_mode: String,
    session_id: Option<String>,
    system: Option<String>,
    user_message: String,
) -> Result<(), String> {
    let _ = chat_id; // reserved for future per-chat scoping.

    if user_message.trim().is_empty() {
        return Err("user_message is empty".into());
    }
    if cwd.trim().is_empty() {
        return Err("cwd is required for claude code chats".into());
    }

    let perm = map_permission_mode(&permission_mode);

    let mut cmd = Command::new("claude");
    cmd.current_dir(&cwd)
        .arg("-p")
        .args(["--input-format", "stream-json"])
        .args(["--output-format", "stream-json"])
        .arg("--verbose")
        .arg("--include-partial-messages");

    // For bypass we use the dedicated skip flag — `--permission-mode bypassPermissions`
    // alone does not actually disable prompts in -p mode.
    if perm == "bypassPermissions" {
        cmd.arg("--dangerously-skip-permissions");
    } else {
        cmd.args(["--permission-mode", perm]);
    }

    if let Some(sid) = session_id.as_deref().filter(|s| !s.is_empty()) {
        cmd.args(["--resume", sid]);
    }
    if let Some(sys) = system.as_deref().filter(|s| !s.is_empty()) {
        cmd.args(["--append-system-prompt", sys]);
    }

    cmd.stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .kill_on_drop(true);

    let mut child: Child = cmd.spawn().map_err(|e| {
        format!(
            "claude binary not found on PATH (or failed to launch). Install with: npm i -g @anthropic-ai/claude-code (error: {e})"
        )
    })?;

    let stdin = child
        .stdin
        .take()
        .ok_or_else(|| "failed to capture child stdin".to_string())?;
    let stdout = child
        .stdout
        .take()
        .ok_or_else(|| "failed to capture child stdout".to_string())?;
    let stderr = child
        .stderr
        .take()
        .ok_or_else(|| "failed to capture child stderr".to_string())?;

    let event_topic = format!("claude://{}/event", request_id);
    let stderr_topic = format!("claude://{}/stderr", request_id);
    let exit_topic = format!("claude://{}/exit", request_id);

    // Write the single user turn as one stream-json line, then drop stdin
    // so the CLI knows there are no further turns this invocation. Any
    // follow-up turn comes as a fresh subprocess with --resume.
    {
        let line = json!({
            "type": "user",
            "message": {
                "role": "user",
                "content": [{ "type": "text", "text": user_message }]
            }
        })
        .to_string();
        let mut stdin = stdin;
        stdin
            .write_all(line.as_bytes())
            .await
            .map_err(|e| format!("write user turn: {e}"))?;
        stdin
            .write_all(b"\n")
            .await
            .map_err(|e| format!("write newline: {e}"))?;
        stdin.shutdown().await.ok();
    }

    let (kill_tx, mut kill_rx) = oneshot::channel::<()>();
    {
        let mut runs = state.runs.lock();
        runs.insert(
            request_id.clone(),
            RunHandle {
                kill: Some(kill_tx),
            },
        );
    }

    // stdout reader — emits each JSONL event as a Tauri event.
    {
        let app = app.clone();
        let topic = event_topic.clone();
        tokio::spawn(async move {
            let mut reader = BufReader::new(stdout).lines();
            loop {
                match reader.next_line().await {
                    Ok(Some(line)) => {
                        if line.trim().is_empty() {
                            continue;
                        }
                        let payload: serde_json::Value =
                            serde_json::from_str(&line).unwrap_or_else(|_| {
                                json!({ "type": "raw", "text": line })
                            });
                        let _ = app.emit(&topic, payload);
                    }
                    Ok(None) => break,
                    Err(_) => break,
                }
            }
        });
    }

    // stderr reader.
    {
        let app = app.clone();
        let topic = stderr_topic.clone();
        tokio::spawn(async move {
            let mut reader = BufReader::new(stderr).lines();
            while let Ok(Some(line)) = reader.next_line().await {
                let _ = app.emit(&topic, line);
            }
        });
    }

    // Wait task — also watches the kill channel.
    {
        let app = app.clone();
        let topic = exit_topic.clone();
        let runs = state.runs.clone();
        let req = request_id.clone();
        tokio::spawn(async move {
            let exit = tokio::select! {
                res = child.wait() => match res {
                    Ok(status) => json!({
                        "code": status.code(),
                        "killed": false,
                    }),
                    Err(e) => json!({ "error": format!("wait failed: {e}"), "killed": false }),
                },
                _ = &mut kill_rx => {
                    let _ = child.start_kill();
                    let _ = child.wait().await;
                    json!({ "code": null, "killed": true })
                }
            };
            let _ = app.emit(&topic, exit);
            runs.lock().remove(&req);
        });
    }

    Ok(())
}

#[tauri::command]
pub fn claude_cancel(state: State<'_, AgentState>, request_id: String) -> Result<(), String> {
    let mut runs = state.runs.lock();
    if let Some(handle) = runs.get_mut(&request_id) {
        if let Some(tx) = handle.kill.take() {
            let _ = tx.send(());
        }
    }
    Ok(())
}
